name: quiz_no_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+1
  path: ^1.8.4
  path_provider: ^2.0.14
  image_picker: ^1.2.0
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar_placeholder.png
